### ISSUE TITLE
在Windows无法安装问题

### ISSUE THREAD

**Issue by evolcano** [zjunlp/KnowLM#51]
我是一个新手，对安装不是很熟悉。我在Windows的Anaconda中，或者Windows的Linux子系统中按照操作步骤安装，总会提示如下问题：

> (zhixi) PS E:\BaiduSyncdisk\deepkellm\KnowLM> python examples/generate_lora_web.py --base_model ./zhixi-base --lora_weights ./zhixi-lora
C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C'), WindowsPath('/Users/ehmy/.conda/envs/zhixi/lib')}
  warn(msg)
C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: C:\Users\ehmy\.conda\envs\zhixi did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "E:\BaiduSyncdisk\deepkellm\KnowLM\examples\generate_lora_web.py", line 8, in <module>
    from peft import PeftModel
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\peft\tuners\lora.py", line 36, in <module>
    import bitsandbytes as bnb
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\ehmy\.conda\envs\zhixi\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

我反复安装了3天，包括对CUDA Toolskit 降级到11.6，总是出现上述的问题。并且在电脑上，找不到 libcudart.so 这个文件。
我确定CUDA 的驱动 和 CUDA Toolskit 都是安装好的，并且Pytorch也安装完成，可以通过如下脚本验证：

> import torch
print(torch.cuda.is_available())    #cuda是否可用
print(torch.version.cuda)            #cuda版本
print(torch.cuda.get_device_name(0)) #返回设备索引
print(torch.cuda.device_count())     # 返回GPU的数量
print(torch.cuda.current_device())   # 返回当前设备索引

我不清楚是不是不能在Windows上安装，或者在下述安装步骤之外，还有其他隐含的步骤？
> conda create -n zhixi python=3.9 -y
conda activate zhixi
pip install torch==1.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
pip install -r requirements.txt

谢谢！

**Comment by MikeDean2367** [comment]
您好，根据[此处](https://www.bilibili.com/read/cv23807024/)的第10步，似乎`bitsandbytes`不支持windows，您可以参考一下链接里提供的方法。如若还是不行，请告知我 :)

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by evolcano** [comment]
@MikeDean2367 @zxlzr 感谢两位的回复。我在Windows 11 下面安装了Anaconda，在Windows 11 下的Linux子系统也安装了，总之怎么都不行，都是同样的错误，libcudart.so 找不到。envs\zhixi\lib\site-packages\bitsandbytes\cuda_setup\main.py  好像路径解析有问题，替换成 libbitsandbytes_cuda116.so 任然报错。

如果有在Windows或者Windows Linux下的安装步骤，请给与提示。非常感谢！
