### ISSUE TITLE
关于显存不足，进行llama.cpp进行量化的问题

### ISSUE THREAD

**Issue by jia95812** [zjunlp/KnowLM#73]
你好，
我的环境是13th Gen Intel(R) Core(TM) i9-13900HX   2.20 GHz，内存64G，显卡是NVIDIA GeForce RTX 4090 16G显存。
我有两个问题：
1、直接运行模型python examples/generate_finetune_web.py --base_model ./model/knowlm-13b-base-v1.0
总是报CUDA memory不足的问题，想问需要什么样的环境才能运行模型？
2、将knowlm-13b-zhixi模型进行llama.cpp进行量化，生成ggml-model-q4_0.gguf
采用python examples/generate_finetune_web.py --base_model ./model/knowlm-13b-base-v1.0/ggml-model-q4_0.gguf
进行启动，这样使用正确吗？
但会报一个错误
  File "F:\KnowLM-main\examples\generate_finetune_web.py", line 166, in <module>
    fire.Fire(main)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "F:\KnowLM-main\examples\generate_finetune_web.py", line 44, in main
    tokenizer = LlamaTokenizer.from_pretrained(base_model)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\models\llama\tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\models\llama\tokenization_llama.py", line 168, in get_spm_processor
    model = model_pb2.ModelProto.FromString(sp_model)
google.protobuf.message.DecodeError: Error parsing message with type 'sentencepiece.ModelProto'

**Comment by MikeDean2367** [comment]
您好，关于第一个问题，我们的模型需要至少26GB的显存才能跑起来，鉴于您有较大的内存，您可以在cpu上运行，代价是牺牲速度，您可以在[第24行](https://github.com/zjunlp/KnowLM/blob/main/examples/generate_lora_web.py#L24)添加`device="cpu"`，从而在cpu上运行。

关于第二个问题，量化后的模型的正确使用方法请参考[此处](https://github.com/zjunlp/KnowLM/blob/main/README_ZH.md#14-llamacpp%E9%87%8F%E5%8C%96)的最后一行内容：
 **在具体运行的时候，请修改[此脚本](https://github.com/ggerganov/llama.cpp/blob/master/examples/alpaca.sh)的模型路径即可。**

**Comment by zxlzr** [comment]
请问您问题是否已解决？

**Comment by jia95812** [comment]
你好，关于第一个问题，我按照你的说法，在[第24行]添加device="cpu"，可以启动，但提交运行任务的时候，会报以下错误，还麻烦看一下：
D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\generation\configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.3` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\generation\configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.75` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\generation\configuration_utils.py:377: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `40` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\generation\configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.3` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\generation\configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.75` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\generation\configuration_utils.py:377: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `40` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\KnowLM-main\examples\generate_finetune_web.py", line 98, in evaluate
    generation_output = model.generate(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\generation\utils.py", line 1675, in generate
    return self.beam_search(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\generation\utils.py", line 3014, in beam_search
    outputs = self(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\models\llama\modeling_llama.py", line 809, in forward
    outputs = self.model(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\models\llama\modeling_llama.py", line 697, in forward
    layer_outputs = decoder_layer(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\models\llama\modeling_llama.py", line 413, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers-4.33.0.dev0-py3.9.egg\transformers\models\llama\modeling_llama.py", line 310, in forward
    query_states = self.q_proj(hidden_states)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by MikeDean2367** [comment]
您好，根据您的报错信息，您的transformers的版本是4.33.0，在[requirements.txt](https://github.com/zjunlp/KnowLM/blob/main/requirements.txt)中有说明是4.28.1的版本，请按照步骤进行安装。如果有其他问题，请告知我 :)

**Comment by jia95812** [comment]
我已经按照环境要求，将所有版本进行了修正，所有要求的都符合要求。我的环境为：
# Name                    Version                   Build  Channel
absl-py                   1.2.0                    pypi_0    pypi
accelerate                0.17.1                   pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aenum                     3.1.12                   pypi_0    pypi
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.0.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4              pyhd3eb1b0_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
asttokens                 2.0.5                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
basicsr                   1.4.2                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bitsandbytes              0.37.2                   pypi_0    pypi
bitsandbytes-windows      0.37.5                   pypi_0    pypi
blas                      1.0                         mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
blendmodes                2022                     pypi_0    pypi
blosc                     1.21.3               h6c2663c_0
boltons                   23.0.0                   pypi_0    pypi
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py39hb82d6ee_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
bzip2                     1.0.8                he774522_0
ca-certificates           2023.05.30           haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cachetools                5.2.0                    pypi_0    pypi
certifi                   2023.7.22        py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.15.1           py39h2bbff1b_3    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cfitsio                   3.470                h2bbff1b_7
charls                    2.2.0                h6c2663c_0
charset-normalizer        2.1.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
clean-fid                 0.1.35                   pypi_0    pypi
click                     8.0.4            py39haa95532_0
cloudpickle               2.2.1            py39haa95532_0
colorama                  0.4.5                    pypi_0    pypi
cryptography              41.0.2           py39hac1b9e3_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cuda-cccl                 12.2.140                      0    nvidia
cuda-cudart               11.8.89                       0    nvidia
cuda-cudart-dev           11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-libraries-dev        11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvrtc-dev            11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-profiler-api         12.2.140                      0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cudatoolkit               11.3.1               h59b6b97_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.11.0                   pypi_0    pypi
cytoolz                   0.12.0           py39h2bbff1b_0
dask-core                 2023.6.0         py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
decorator                 5.1.1                    pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
executing                 0.9.1                    pypi_0    pypi
facexlib                  0.3.0                    pypi_0    pypi
fastapi                   0.95.1                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
font-roboto               0.0.1                    pypi_0    pypi
fonts                     0.0.3                    pypi_0    pypi
fonttools                 4.34.4                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0         py39haa95532_0
future                    0.18.3                   pypi_0    pypi
gfpgan                    1.3.8                    pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
google-auth               2.9.1                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
gradio                    3.29.0                   pypi_0    pypi
gradio-client             0.2.4                    pypi_0    pypi
grpcio                    1.54.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  0.17.0                   pypi_0    pypi
httpx                     0.24.0                   pypi_0    pypi
huggingface-hub           0.17.1                   pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
idna                      3.4              py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
imagecodecs               2021.8.26        py39h319e4f4_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
imageio                   2.26.0           py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
importlib-metadata        4.12.0                   pypi_0    pypi
imread                    0.7.4            py39h1269fff_1    conda-forge
inflection                0.5.1                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46319    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ipython                   8.4.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2            py39haa95532_0
jpeg                      9e                   h8ffe710_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
js2py                     0.74                     pypi_0    pypi
jsonmerge                 1.9.0                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jxrlib                    1.1                  he774522_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
kiwisolver                1.4.4                    pypi_0    pypi
kornia                    0.6.12                   pypi_0    pypi
lark                      1.1.5                    pypi_0    pypi
lcms2                     2.12                 h83e58a3_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lerc                      3.0                  hd77b12b_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libaec                    1.0.4                h33f27b4_1
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libcublas                 11.11.3.6                     0    nvidia
libcublas-dev             11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufft-dev              10.9.0.58                     0    nvidia
libcurand                 10.3.3.141                    0    nvidia
libcurand-dev             10.3.3.141                    0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusolver-dev           11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libcusparse-dev           11.7.5.86                     0    nvidia
libdeflate                1.17                 h2bbff1b_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libnpp                    11.8.0.86                     0    nvidia
libnpp-dev                11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libnvjpeg-dev             11.9.0.86                     0    nvidia
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.0                h6c2663c_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuv                     1.44.2               h2bbff1b_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libwebp                   1.3.1                hcfcfb64_0    conda-forge
libwebp-base              1.3.1                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
libzopfli                 1.0.3                ha925a31_0
linkify-it-py             2.0.2                    pypi_0    pypi
llvmlite                  0.40.0                   pypi_0    pypi
lmdb                      1.4.1                    pypi_0    pypi
locket                    1.0.0            py39haa95532_0
lz4-c                     1.9.4                h2bbff1b_0
m2w64-gcc-libgfortran     5.3.0                         6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gcc-libs            5.3.0                         7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gcc-libs-core       5.3.0                         7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gmp                 6.1.0                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
markdown                  3.4.1                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.1            py39h2bbff1b_0
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h8bd8f75_46356    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0            py39h2bbff1b_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.3.6            py39hf11a4ad_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.2.2            py39hf11a4ad_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mpmath                    1.3.0            py39haa95532_0
msys2-conda-epoch         20160418                      1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
multidict                 6.0.4                    pypi_0    pypi
networkx                  3.1              py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numba                     0.57.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
opencv-contrib-python     4.7.0.72                 pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openjpeg                  2.4.0                hb211442_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openssl                   3.0.9                h2bbff1b_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
orjson                    3.8.12                   pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.2.0              pyhd3eb1b0_1
pickleshare               0.7.5                    pypi_0    pypi
piexif                    1.1.3                    pypi_0    pypi
pillow                    9.2.0            py39ha53f419_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pip                       23.2.1           py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pipwin                    0.5.2                    pypi_0    pypi
pooch                     1.4.0              pyhd3eb1b0_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
prompt-toolkit            3.0.30                   pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pure-eval                 0.2.2                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pydantic                  1.10.7                   pypi_0    pypi
pydeprecate               0.3.2                    pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyjsparser                2.7.1                    pypi_0    pypi
pyopenssl                 23.2.0           py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyparsing                 3.0.9                    pypi_0    pypi
pyprind                   2.11.3                   pypi_0    pypi
pyproject                 1.3.1                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysmartdl                 1.3.4                    pypi_0    pypi
pysocks                   1.7.1            py39hcbf5309_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python                    3.9.17               h1aa4202_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
python_abi                3.9                      2_cp39    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch-cuda              11.8                 h24eeafa_5    pytorch
pytorch-mutex             1.0                        cuda    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytz                      2022.1                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pywavelets                1.4.1            py39h2bbff1b_0
pyyaml                    6.0                      pypi_0    pypi
realesrgan                0.3.0                    pypi_0    pypi
regex                     2023.5.5                 pypi_0    pypi
requests                  2.31.0           py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests-oauthlib         1.3.1                    pypi_0    pypi
resize-right              0.0.2                    pypi_0    pypi
rich                      13.3.5                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.3.1                    pypi_0    pypi
scikit-image              0.19.3           py39hd77b12b_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scipy                     1.9.0                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                68.0.0           py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
snappy                    1.1.9                h6c2663c_0
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
stack-data                0.3.0                    pypi_0    pypi
starlette                 0.26.1                   pypi_0    pypi
sympy                     1.11.1           py39haa95532_0
tb-nightly                2.12.0a20230126          pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
thop                      0.1.1-2207130030          pypi_0    pypi
tifffile                  2021.7.2           pyhd3eb1b0_2
timm                      0.4.12                   pypi_0    pypi
tk                        8.6.12               h2bbff1b_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tokenizers                0.13.3                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0           py39haa95532_0
torch                     1.13.1+cu116             pypi_0    pypi
torchaudio                2.0.2                    pypi_0    pypi
torchdiffeq               0.2.3                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.3.0                    pypi_0    pypi
trampoline                0.1.2                    pypi_0    pypi
transformers              4.28.1                   pypi_0    pypi
typing_extensions         4.7.1            py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tzdata                    2023.3                   pypi_0    pypi
tzlocal                   4.3                      pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
ucrt                      10.0.20348.0         haa95532_0
ultralytics               8.0.147                  pypi_0    pypi
urllib3                   1.26.16          py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
uvicorn                   0.22.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  2.2.1                    pypi_0    pypi
wheel                     0.38.4           py39haa95532_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
win_inet_pton             1.1.0            py39hcbf5309_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxau               1.0.9                hcd874cb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.4.2                h8cc25b3_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yaml                      0.2.5                he774522_0
yapf                      0.33.0                   pypi_0    pypi
yarl                      1.9.2                    pypi_0    pypi
zfp                       0.5.5                hd77b12b_6    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                hd43e919_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
但依然会报这个错误：
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\KnowLM-main\examples\generate_finetune_web.py", line 98, in evaluate
    generation_output = model.generate(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers\generation\utils.py", line 1524, in generate
    return self.beam_search(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers\generation\utils.py", line 2810, in beam_search
    outputs = self(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\anaconda3\envs\knowlm_new_env\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by MikeDean2367** [comment]
您好，非常感谢您的反馈。经过我们的检查，是由于目前cpu上不支持半精度的模型，因此我们将其转换成全精度格式即可正常运行。我们已经修复这个问题，您可以重新下载进行测试。如果您还有其他问题，请告知我:)

**Comment by jia95812** [comment]
您好，经过测试，device="cpu"，python examples/generate_finetune_web.py --base_model ./model/knowlm-13b-base-v1.0中产生的RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'问题解决了。
但是如果在generate_lora_web.py中设置device="cpu"，并使用python examples/generate_lora_web.py --base_model ./model/knowlm-13b-zhixi，仍然会产生RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'的错误，估计是上次修改中没有完全修改完善，请帮忙查看一下，非常感谢！
